-- insert admin (username a, password aa)
INSERT INTO IWUser (id, enabled, roles, username, password)
VALUES (1, TRUE, 'ADMIN,USER', 'a',
    '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
INSERT INTO IWUser (id, enabled, roles, username, password)
VALUES (2, TRUE, 'USER', 'b',
    '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');



insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (3, 'Barney', 'Potticary', 'bpotticary0@narod.ru', 'bpotticary0', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Hungarian', '77 Dakota Court', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (4, 'Consuelo', 'Persicke', 'cpersicke1@1und1.de', 'cpersicke1', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Punjabi', '17706 Anhalt Court', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (5, 'Laverna', 'Polden', 'lpolden2@comcast.net', 'lpolden2', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Assamese', '0 Jenifer Place', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (6, 'Kore', 'Feary', 'kfeary3@desdev.cn', 'kfeary3', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Estonian', '34 Erie Hill', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (7, 'Mathew', 'Borrett', 'mborrett4@altervista.org', 'mborrett4', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Japanese', '0 Shelley Trail', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (8, 'Stan', 'Whatham', 'swhatham5@newyorker.com', 'swhatham5', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'English', '89 Huxley Junction', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (9, 'Henderson', 'Nijssen', 'hnijssen6@reference.com', 'hnijssen6', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Belarusian', '15 Cardinal Way', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (10, 'Leeann', 'Maving', 'lmaving7@cnn.com', 'lmaving7', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Mongolian', '62521 Sachtjen Junction', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (11, 'Kristo', 'Cuttings', 'kcuttings8@amazon.co.uk', 'kcuttings8', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Bengali', '10284 Butternut Terrace', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (12, 'Penny', 'Iacovaccio', 'piacovaccio9@intel.com', 'piacovaccio9', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Georgian', '36 Pierstorff Way', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (13, 'Haskel', 'Conradie', 'hconradiea@ustream.tv', 'hconradiea', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Swedish', '0217 Arizona Way', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (14, 'Galen', 'Garvey', 'ggarveyb@imgur.com', 'ggarveyb', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Greek', '9390 Schlimgen Court', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (15, 'Findley', 'Bexley', 'fbexleyc@nationalgeographic.com', 'fbexleyc', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Irish Gaelic', '33524 Hallows Park', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (16, 'Seka', 'Warwicker', 'swarwickerd@reuters.com', 'swarwickerd', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Guaraní', '25417 Oriole Lane', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (17, 'Harriot', 'Petrelli', 'hpetrellie@sogou.com', 'hpetrellie', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Czech', '7 Rieder Crossing', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (18, 'Marabel', 'Lakeman', 'mlakemanf@dagondesign.com', 'mlakemanf', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Khmer', '1237 Dwight Center', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (19, 'Pierette', 'Nial', 'pnialg@so-net.ne.jp', 'pnialg', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Sotho', '25717 Swallow Way', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (20, 'Prince', 'Lutzmann', 'plutzmannh@dedecms.com', 'plutzmannh', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Bosnian', '03355 Barby Terrace', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (21, 'Laetitia', 'Turbard', 'lturbardi@fda.gov', 'lturbardi', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'English', '393 Vidon Hill', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
insert into IWUSER (id, first_name, last_name, email, username, birthdate, enabled, description, languages, location, rating, roles, status, password) values (22, 'Julie', 'Dollin', 'jdollinj@netvibes.com', 'jdollinj', PARSEDATETIME('12/03/2013','dd/MM/yyyy'), TRUE, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Filipino', '0443 Maple Wood Avenue', 0, 'USER', 'ACTIVE', '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');


-- start id numbering from a value that is larger than any assigned above
ALTER SEQUENCE "PUBLIC"."GEN" RESTART WITH 1024;
